--- #YAML:1.0
name: SQL-Interpolate
version: 0.31_01
author:
  - David Manura (http://math2.org/david/contact)
abstract: |-
  Simplified interpolation of Perl variables into SQL statements
license: perl
recommends:
  Filter::Simple: 0
  Text::Balanced: '>= 1.87'
provides:
  DBIx::Interpolate:
    file: lib/DBIx/Interpolate.pm
    version: 0.31_01
  DBIx::Interpolate::STX:
    file: lib/DBIx/Interpolate.pm
    version: 0.31_01
  SQL::Interpolate:
    file: lib/SQL/Interpolate.pm
    version: 0.31_01
  SQL::Interpolate::And:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Filter:
    file: lib/SQL/Interpolate/Filter.pm
    version: 0.30
  SQL::Interpolate::Fragment:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::If:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Link:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Literal:
    file: lib/SQL/Interpolate.pm
    version: 0.31_01
  SQL::Interpolate::Macro:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Or:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Paren:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Rel:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::RelProcessor:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::SQL:
    file: lib/SQL/Interpolate/Filter.pm
    version: 0.30
  SQL::Interpolate::SQLFilter:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.30
  SQL::Interpolate::Variable:
    file: lib/SQL/Interpolate.pm
    version: 0.31_01
generated_by: Module::Build version 0.2607
