--- #YAML:1.0
name: SQL-Interpolate
version: 0.40
author:
  - David Manura (http://math2.org/david/contact)
  - Mark Stosberg <mark@summersault.com>
abstract: Interpolate Perl variables into SQL statements
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1
recommends:
  Filter::Simple: 0
  Scalar::Util: 0
  Text::Balanced: 1.87
provides:
  DBIx::Interpolate:
    file: lib/DBIx/Interpolate.pm
    version: 0.40
  DBIx::Interpolate::STX:
    file: lib/DBIx/Interpolate.pm
  DBIx::Interpolate::db:
    file: lib/DBIx/Interpolate.pm
  SQL::Interpolate:
    file: lib/SQL/Interpolate.pm
    version: 0.40
  SQL::Interpolate::And:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Filter:
    file: lib/SQL/Interpolate/Filter.pm
    version: 0.40
  SQL::Interpolate::If:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Link:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Macro:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.40
  SQL::Interpolate::Or:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Paren:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Rel:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::RelProcessor:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::SQL:
    file: lib/SQL/Interpolate.pm
  SQL::Interpolate::SQLFilter:
    file: lib/SQL/Interpolate/Macro.pm
  SQL::Interpolate::Variable:
    file: lib/SQL/Interpolate.pm
generated_by: Module::Build version 0.2807
meta-spec:
  url: |-
    http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
