--- #YAML:1.0
name: SQL-Interpolate
version: 0.31
author:
  - David Manura (http://math2.org/david/contact)
abstract: Simplified interpolation of Perl variables into SQL statements
license: perl
generated_by: Module::Build version 0.2608, without YAML.pm
