---
name: SQL-Interpolate
version: 0.33
author:
  - David Manura (http://math2.org/david/contact)
abstract: Interpolate Perl variables into SQL statements
license: perl
recommends:
  Filter::Simple: 0
  Text::Balanced: 1.87
provides:
  DBIx::Interpolate:
    file: lib/DBIx/Interpolate.pm
    version: 0.33
  DBIx::Interpolate::STX:
    file: lib/DBIx/Interpolate.pm
    version: 0.33
  SQL::Interpolate:
    file: lib/SQL/Interpolate.pm
    version: 0.33
  SQL::Interpolate::And:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Filter:
    file: lib/SQL/Interpolate/Filter.pm
    version: 0.33
  SQL::Interpolate::If:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Link:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Macro:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Or:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Paren:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Rel:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::RelProcessor:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::SQL:
    file: lib/SQL/Interpolate.pm
    version: 0.33
  SQL::Interpolate::SQLFilter:
    file: lib/SQL/Interpolate/Macro.pm
    version: 0.33
  SQL::Interpolate::Variable:
    file: lib/SQL/Interpolate.pm
    version: 0.33
generated_by: Module::Build version 0.2611
